# Generated by Django 4.1.3 on 2022-12-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('diskripsi', models.TextField()),
                ('harga', models.IntegerField(null=True)),
            ],
        ),
    ]
